/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HaBaseButton: typeof import('./../app/components/ha/base/HaBaseButton.vue')['default']
    HaBaseInput: typeof import('./../app/components/ha/base/HaBaseInput.vue')['default']
    HaContainer: typeof import('./../app/components/ha/HaContainer.vue')['default']
    HaDialog: typeof import('./../app/components/ha/HaDialog.vue')['default']
    HaDialogElement: typeof import('./../app/components/ha/HaDialogElement.vue')['default']
    HaHamburger: typeof import('./../app/components/ha/HaHamburger.vue')['default']
    HaImage: typeof import('./../app/components/ha/HaImage.vue')['default']
    HaLabel: typeof import('./../app/components/ha/HaLabel.vue')['default']
    HaLink: typeof import('./../app/components/ha/HaLink.vue')['default']
    HaLoading: typeof import('./../app/components/ha/HaLoading.vue')['default']
    HaLoadingIcon: typeof import('./../app/components/ha/HaLoadingIcon.vue')['default']
    HaModal: typeof import('./../app/components/ha/HaModal.vue')['default']
    HaSelectBox: typeof import('./../app/components/ha/HaSelectBox.vue')['default']
    HaSkewBackground: typeof import('./../app/components/ha/HaSkewBackground.vue')['default']
    HaTag: typeof import('./../app/components/ha/HaTag.vue')['default']
    HaTextarea: typeof import('./../app/components/ha/HaTextarea.vue')['default']
    HaVideo: typeof import('./../app/components/ha/HaVideo.vue')['default']
    HmAccordion: typeof import('./../app/components/hm/HmAccordion.vue')['default']
    HmAutoCarousel: typeof import('./../app/components/hm/HmAutoCarousel.vue')['default']
    HmButton: typeof import('./../app/components/hm/button/HmButton.vue')['default']
    HmButtonClose: typeof import('./../app/components/hm/button/HmButtonClose.vue')['default']
    HmButtonFavorite: typeof import('./../app/components/hm/button/HmButtonFavorite.vue')['default']
    HmClipping: typeof import('./../app/components/hm/HmClipping.vue')['default']
    HmDialogElement: typeof import('./../app/components/hm/HmDialogElement.vue')['default']
    HmIconUser: typeof import('./../app/components/hm/icon/HmIconUser.vue')['default']
    HmInputCheckbox: typeof import('./../app/components/hm/input/HmInputCheckbox.vue')['default']
    HmInputDatetime: typeof import('./../app/components/hm/input/HmInputDatetime.vue')['default']
    HmInputFile: typeof import('./../app/components/hm/input/HmInputFile.vue')['default']
    HmInputRadio: typeof import('./../app/components/hm/input/HmInputRadio.vue')['default']
    HmInputRadioChangeable: typeof import('./../app/components/hm/input/HmInputRadioChangeable.vue')['default']
    HmInputSingleImage: typeof import('./../app/components/hm/input/HmInputSingleImage.vue')['default']
    HmInputText: typeof import('./../app/components/hm/input/HmInputText.vue')['default']
    HmMenuExample: typeof import('./../app/components/hm/HmMenuExample.vue')['default']
    HmNoteList: typeof import('./../app/components/hm/HmNoteList.vue')['default']
    HmPaging: typeof import('./../app/components/hm/HmPaging.vue')['default']
    HmPicture: typeof import('./../app/components/hm/HmPicture.vue')['default']
    HmPopup: typeof import('./../app/components/hm/HmPopup.vue')['default']
    HmSkeletonScreen: typeof import('./../app/components/hm/HmSkeletonScreen.vue')['default']
    HmSlider: typeof import('./../app/components/hm/HmSlider.vue')['default']
    HmSliderItem: typeof import('./../app/components/hm/HmSliderItem.vue')['default']
    HmSocialShareLink: typeof import('./../app/components/hm/HmSocialShareLink.vue')['default']
    HmTab: typeof import('./../app/components/hm/HmTab.vue')['default']
    HmTsx: typeof import('./../app/components/hm/HmTsx.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
