name: <Main> Coverage by Vitest

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review]
    branches: ['develop']

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.23
      - run: bun install
      - run: cd layers/main && bun install

      # カバレッジを、PRコメントとコミットステータスとしてポストする
      - run: .github/workflows/post-coverage.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event.pull_request.head.sha || github.sha }} ${{ github.event.pull_request.number }} $GITHUB_REPOSITORY layers/main "Main"
